name: AutoDeploy
on:
  push:
    branches:
      - master

jobs:
  autodeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - run: npm install
      - run: aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
      - run: aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: aws configure set default.region eu-west-1
      - run: AWS_REGION=${{secrets.AWS_REGION}} npm run build
      - run: AWS_REGION=${{secrets.AWS_REGION}} AWS_BUCKET_NAME=${{secrets.AWS_BUCKET_NAME}} npm run deploy